# fly.toml app configuration file generated for fermentwatch-api on 2026-05-29T08:32:55+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fermentwatch-api'
primary_region = 'cdg'

[build]
  dockerfile = 'Dockerfile'

[env]
  ASPNETCORE_ENVIRONMENT = 'Production'
  ASPNETCORE_URLS = 'http://+:8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512